"AWSTemplateFormatVersion" : "2010-09-09"
Description: EC2 with ASG and Launch Configuration cloudformationscript 

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access 
    Default: "xyz-keypair"

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.medium
    AllowedValues: [t2.micro, t2.small, t2.medium, t2.large, m3.medium, m3.large,
      m3.xlarge, m3.2xlarge, m4.large, m4.xlarge, m4.2xlarge, m4.4xlarge, m4.10xlarge,
      c4.large, c4.xlarge, c4.2xlarge, c4.4xlarge, c4.8xlarge, c3.large, c3.xlarge,
      c3.2xlarge, c3.4xlarge, c3.8xlarge, r3.large, r3.xlarge, r3.2xlarge, r3.4xlarge,
      r3.8xlarge, i2.xlarge, i2.2xlarge, i2.4xlarge, i2.8xlarge]
    ConstraintDescription: Please choose a valid instance type.

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Select a VPC that allows instances access to the Internet.
    Default: "vpc-xyz"

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Select the Subnet in your selected VPC.
    Default: "subnet-xyz"

  SecurityGroup:
    Description: Select the Security Group to use for the ECS cluster hosts
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-xyz
    AllowedValues: 
    - sg-xyz

Resources:
  LaunchConfig: 
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties: 
      InstanceType: !Ref InstanceType
      ImageId: ami-xyz
      KeyName: !Ref KeyName
      SecurityGroups:
       - !Ref SecurityGroup
      LaunchConfigurationName: ASG-launch-config
      

  GeoASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref SubnetId
      DesiredCapacity: 1
      LaunchConfigurationName: !Ref LaunchConfig
      MaxSize: 2
      MinSize: 1